/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callCommitEarly
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callCommitEarly
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision1
 * Signature: (IJIIJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision1
  (JNIEnv *, jobject, jint, jlong, jint, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision2
 * Signature: (JIJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision2
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision3
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision3
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision4
 * Signature: (IJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision4
  (JNIEnv *, jobject, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision5
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision5
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBeale
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBeale
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callFreudensteinRoth
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callFreudensteinRoth
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTheta
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTheta
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callHelicalValley
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callHelicalValley
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPowell
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPowell
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRosenbrock
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRosenbrock
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callWood
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callWood
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
