$binPath = '/root/eclipseWorkspace/cn.nju.seg.atg/bin'
$moveToFolderPath = '/root/eclipseWorkspace/ATGWrapperCpp/src'
$targetClassName = 'cn.nju.seg.atg.callCPP.CallCPP'
$targetHeaderFileName = 'cn_nju_seg_atg_callCPP_CallCPP.h'

Write-Host 'Note: The JNI header is generated by JVM class file, so you should compile the java source file first.'

$currentLocation = Get-Location

# set location to bin folder
# Set-Location $binPath

# run javah
javah -classpath $binPath -jni $targetClassName

# move generated cpp header file
Move-Item -Path "./$targetHeaderFileName" -Destination $moveToFolderPath -Force

# restore location
# $currentLocation | Set-Location

