/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callEi
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callEi
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGammp
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGammp
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callJulday
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callJulday
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessj
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessj
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callExpint
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callExpint
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callCaldat
 * Signature: (IIIILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callCaldat
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPlgndr
 * Signature: (IIDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPlgndr
  (JNIEnv *, jobject, jint, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessik
 * Signature: (DDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessik
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBetacf
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBetacf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBrent
 * Signature: (DDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callZbrent
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callZbrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan2
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan3
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan3
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callDbrent
 * Signature: (DDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callDbrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark01
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark01
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark02
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark02
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark03
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark03
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark04
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark04
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark05
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark05
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark06
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark06
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark07
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark07
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark08
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark08
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark09
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark09
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark10
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark10
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark11
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark12
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark12
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark13
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark13
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark14
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark14
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark15
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark15
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark16
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark16
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark17
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark17
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark18
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark18
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark19
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark19
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark20
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark20
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark21
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark21
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark22
 * Signature: (DDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark22
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark23
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark23
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark25
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark25
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark26
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark26
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark27
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark27
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark29
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark29
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark32
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark32
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark33
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark33
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark34
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark34
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark35
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark35
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark38
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark38
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark39
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark39
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark40
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark40
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark41
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark41
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark42
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark42
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark43
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark43
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark44
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark44
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark45
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark45
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark46
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark46
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark47
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark47
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark48
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark48
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark49
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark49
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark50
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark50
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark52
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark52
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark53
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark53
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark56
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark56
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark61
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark61
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark62
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark62
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark70
 * Signature: (DDDDDDDDDDDDDDDDDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark70
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark71
 * Signature: (DDDDDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark71
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark72
 * Signature: (DDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark72
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark73
 * Signature: (DDDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark73
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark74
 * Signature: (DDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark74
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark75
 * Signature: (DDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark75
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark76
 * Signature: (DDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark76
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark77
 * Signature: (DDDDDDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark77
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark78
 * Signature: (DDDDDIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark78
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark79
 * Signature: (DDDDILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark79
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark80
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark80
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark81
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark81
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark82
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark82
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark83
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark83
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark84
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark84
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark91
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark91
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callCommitEarly
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callCommitEarly
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision1
 * Signature: (IJIIJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision1
  (JNIEnv *, jobject, jint, jlong, jint, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision2
 * Signature: (JIJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision2
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision3
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision3
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision4
 * Signature: (IJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision4
  (JNIEnv *, jobject, jint, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTestCollision5
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTestCollision5
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBeale
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBeale
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callFreudensteinRoth
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callFreudensteinRoth
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callHelicalValley
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callHelicalValley
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPowell
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPowell
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRosenbrock
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRosenbrock
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callWood
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callWood
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callDart
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callDart
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPower
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPower
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callConflict
 * Signature: (DDDDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callConflict
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTurnLogic
 * Signature: (DDDDDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTurnLogic
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMysin
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMysin
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callStat
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callStat
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    prepareStat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_prepareStat
  (JNIEnv *, jobject);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark28
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark28
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark30
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark30
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark31
 * Signature: (DLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark31
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark36
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark36
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark37
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark37
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark51
 * Signature: (DDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark51
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark54
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark54
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark55
 * Signature: (DDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark55
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark57
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark57
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark58
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark58
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark59
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark59
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark60
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark60
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark63
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark63
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark64
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark64
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark65
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark65
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark66
 * Signature: (DDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark66
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark67
 * Signature: (DDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark67
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark68
 * Signature: (DDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark68
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBenchmark69
 * Signature: (DDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBenchmark69
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTest
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTest
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTcasRun
 * Signature: (IIIIIIIIIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTcasRun
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
