/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callStat
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callStat
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
