/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi0
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi0
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi1
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi1
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessk0
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessk0
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessk1
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessk1
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBetai
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBetai
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callFlmoon
 * Signature: (IIIDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callFlmoon
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGammp
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGammp
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGammq
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGammq
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGcf
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGcf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGser
 * Signature: (DDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGser
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidexp
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidexp
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidinf
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidinf
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidpnt
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidpnt
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidsql
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidsql
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidsqu
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidsqu
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callProbks
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callProbks
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPythag
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPythag
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan0
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan0
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callSphbes
 * Signature: (IDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callSphbes
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTrapzd
 * Signature: (DDILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTrapzd
  (JNIEnv *, jobject, jdouble, jdouble, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callZbrac
 * Signature: (DDLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callZbrac
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
