/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callEi
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callEi
  (JNIEnv *, jobject, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGammp
 * Signature: (DDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGammp
  (JNIEnv *, jobject, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callJulday
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callJulday
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessj
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessj
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callExpint
 * Signature: (IDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callExpint
  (JNIEnv *, jobject, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callCaldat
 * Signature: (IIIILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callCaldat
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPlgndr
 * Signature: (IIDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPlgndr
  (JNIEnv *, jobject, jint, jint, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessik
 * Signature: (DDDDDDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessik
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBetacf
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBetacf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBrent
 * Signature: (DDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callZbrent
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callZbrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan2
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan3
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan3
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callDbrent
 * Signature: (DDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callDbrent
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi0
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessi1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessi1
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessk0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessk0
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBessk1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBessk1
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callBetai
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callBetai
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callFlmoon
 * Signature: (IIID)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callFlmoon
  (JNIEnv *, jobject, jint, jint, jint, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGammq
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGammq
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGcf
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGcf
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callGser
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callGser
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidexp
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidexp
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidinf
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidinf
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidpnt
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidpnt
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidsql
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidsql
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMidsqu
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMidsqu
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callProbks
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callProbks
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPythag
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPythag
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callRan0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callRan0
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callSphbes
 * Signature: (IDDDDD)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callSphbes
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTrapzd
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTrapzd
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callZbrac
 * Signature: (DD)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callZbrac
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callExample
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callExample
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callSimExample
 * Signature: (DDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callSimExample
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
