/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nju_seg_atg_callCPP_CallCPP */

#ifndef _Included_cn_nju_seg_atg_callCPP_CallCPP
#define _Included_cn_nju_seg_atg_callCPP_CallCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callDart
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callDart
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callPower
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callPower
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callConflict
 * Signature: (DDDDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callConflict
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callTurnLogic
 * Signature: (DDDDDDDDLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callTurnLogic
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     cn_nju_seg_atg_callCPP_CallCPP
 * Method:    callMysin
 * Signature: (DLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_cn_nju_seg_atg_callCPP_CallCPP_callMysin
  (JNIEnv *, jobject, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
